# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - internal
  - external
  - ../haproxy/bases/configs

patches:
  - target:
      group: ""
      version: v1
      kind: Service
      name: haproxy-ingress-metrics
    path: patch/delete-metrics-service.yaml
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: haproxy-ingress
    path: patch/delete-servicemonitor.yaml
  - target:
      group: ""
      version: v1
      kind: Service
      name: haproxy-ingress-admin
    path: patch/delete-admin-service.yaml
