# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy-ingress-internal-metrics
  namespace: ingress-haproxy
  labels:
    k8s-app: haproxy-ingress
    type: internal
spec:
  endpoints:
    - interval: 10s
      path: /metrics
      port: stat
      scheme: http
  namespaceSelector:
    matchNames:
      - ingress-haproxy
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-ingress
      app.kubernetes.io/instance: haproxy-ingress
      type: internal
