# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

fullnameOverride: haproxy-ingress-external

controller:
  ingressClass: external
  ingressClassResource:
    name: external
    default: false
  podLabels:
    k8s-app: haproxy-ingress
    type: external
  service:
    labels:
      k8s-app: haproxy-ingress
      type: external
    nodePorts:
      http: 30080
      https: 30443
