# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

transformers:
  - ./patch/suffix.yaml

resources:
  - ../../haproxy/bases/controller
  - metrics/service.yaml
  - metrics/servicemonitor.yaml
  - admin/service.yaml

labels:
  - includeSelectors: true
    pairs:
      app: haproxy
      type: external

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: haproxy-ingress
    path: patch/daemonset.yaml
  - target:
      version: v1
      kind: Service
      name: haproxy-ingress
    path: patch/service.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: IngressClass
      name: haproxy
    path: patch/ingressclass.yaml
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: PrometheusRule
      name: haproxy-ingress-controller
    patch: |-
      - op: replace
        path: /metadata/name
        value: haproxy-ingress-metrics-external-rule
