# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# Source: kubernetes-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress
  namespace: ingress-haproxy
  labels:
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/instance: haproxy-ingress
    helm.sh/chart: kubernetes-ingress-1.46.1
    app.kubernetes.io/version: "3.1.14"
    app.kubernetes.io/managed-by: Helm
    k8s-app: haproxy-ingress
  annotations:
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      appProtocol: http
      targetPort: http
      nodePort: 31080
    - name: https
      port: 443
      protocol: TCP
      appProtocol: https
      targetPort: https
      nodePort: 31443
  selector:
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/instance: haproxy-ingress
  externalIPs:
